import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "./font/PretendardVariable.woff2",
  style: "normal",
});

const pretendardJP = localFont({
  src: "./font/PretendardJPVariable.ttf",
  style: "normal",
});

export const metadata: Metadata = {
  title: "SONULOG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendard.className} ${pretendardJP.className} antialiased scroll-smooth`}
      >
        {children}
      </body>
    </html>
  );
}
