import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pretendard = localFont({
  src: "./font/PretendardVariable.woff2",
  style: "normal",
});

const pretendardJP = localFont({
  src: "./font/PretendardJPVariable.ttf",
  style: "normal",
});

export const metadata: Metadata = {
  title: "SONULOG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pretendard.className} ${pretendardJP.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
